name: Babaa Tweet Bot

on:
  schedule:
    - cron: '0 23 * * *'   # JST 08:00
    - cron: '0 3 * * *'    # JST 12:00
    - cron: '0 8 * * *'    # JST 17:00
    - cron: '0 12 * * *'   # JST 21:00
  workflow_dispatch:

jobs:
  babaa_tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write secrets to .env file
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" >> .env
          echo "TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}" >> .env
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> .env
          echo "TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }}" >> .env
          echo "TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN }}" >> .env

      - name: Generate and Post 1 Babaa Tweet
        run: python tweet_bot.py

      - name: Push raw_post to control_center
        run: |
          git clone https://x-access-token:${{ secrets.CONTROL_CENTER_PAT }}@github.com/groovy1985/control_center.git
          mkdir -p control_center/Syntaxtemple/raw_post/baba/
          cp Syntaxtemple/raw_post/baba/*.txt control_center/Syntaxtemple/raw_post/baba/
          cd control_center
          git config user.name "babaa-bot"
          git config user.email "babaa@syntax.temple"
          git add Syntaxtemple/raw_post/baba/
          git commit -m "Add: babaa構文死体 $(date '+%Y-%m-%d %H:%M')" || echo "No changes"
          git push origin main
