name: test_read_trend

on:
  workflow_dispatch:  # 手動実行可能

jobs:
  run-read-trend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install deps
        run: |
          pip install -r requirements.txt

      - name: Load .env
        run: |
          echo "TWITTER_READ_BEARER_TOKEN=${{ secrets.TWITTER_READ_BEARER_TOKEN }}" >> .env
          echo "TWITTER_READ_API_KEY=${{ secrets.TWITTER_READ_API_KEY }}" >> .env
          echo "TWITTER_READ_API_SECRET=${{ secrets.TWITTER_READ_API_SECRET }}" >> .env
          echo "TWITTER_READ_ACCESS_TOKEN=${{ secrets.TWITTER_READ_ACCESS_TOKEN }}" >> .env
          echo "TWITTER_READ_ACCESS_SECRET=${{ secrets.TWITTER_READ_ACCESS_SECRET }}" >> .env

      - name: Run read_trend.py
        run: python read_trend.py
