name: Generate & Post Babaa from Last-Words Repo

on:
  repository_dispatch:
    types: [babaa_post_update_trigger]  # ← 任意のイベント名でOK

jobs:
  generate_and_post_babaa:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: 📁 Checkout repository
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Install dependencies (if any)
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "⚠️ No requirements.txt found, skipping install."
          fi

      - name: 🔍 Show dispatch payload info
        run: |
          echo "Triggered by repo: ${{ github.event.client_payload.repo }}"
          echo "Trigger type: ${{ github.event.client_payload.trigger }}"

      - name: 👵 Run generate_post_lastwords.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
        run: |
          echo "🚀 Starting Babaa post generation..."
          python generate_post_lastwords.py ${{ github.event.client_payload.repo }} ${{ github.event.client_payload.trigger }}
          echo "✅ Babaa post process complete."
