name: Run Babaa Watchers

on:
  workflow_dispatch:
  # 定期実行も可能（例：1時間ごと）
  # schedule:
  #   - cron: '0 * * * *'

jobs:
  run_watchers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install feedparser

      - name: Set environment variables
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }}" >> $GITHUB_ENV
          echo "TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }}" >> $GITHUB_ENV
          echo "TWITTER_ACCESS_TOKEN=${{ secrets.TWITTER_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "TWITTER_ACCESS_SECRET=${{ secrets.TWITTER_ACCESS_SECRET }}" >> $GITHUB_ENV

      - name: Watch poem cemetery
        run: python watcher_poemcemetery.py

      - name: Watch last words
        run: python watcher_lastwords.py

      - name: Watch note RSS
        run: python watcher_note_rss.py
